server:
  http:
    addr: 0.0.0.0:8020
    timeout: 1s
  discord:
    user_token: xxx
    bot_token: xxx
    server_id: "10101"
    channel_id: "01010"
data:
  database:
    driver: mysql
    source: root:root@tcp(127.0.0.1:3306)/test
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
