// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"go-discord/internal/conf"
	"go-discord/internal/server"
	"go-discord/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, data *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	httpServer := server.NewHTTPServer(confServer, logger)
	discordService := service.NewDiscordService(logger, confServer)
	discordServer := server.NewDiscordService(confServer, discordService)
	app := newApp(logger, httpServer, discordServer)
	return app, func() {
	}, nil
}
